import { Providers as RQprovider } from "@/RQ/provider";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import { Providers as ReduxProvider } from "@/redux/provider";
import Massage from "@/components/massage";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " bg-lightprimary bg-center bg-cover min-h-screen"
        }
      >
        <RQprovider>
          <ReduxProvider>
            {children}
            <Massage />
          </ReduxProvider>
        </RQprovider>
      </body>
    </html>
  );
}
